-- Snowflake Database and Schema Setup for Fraud Detection Pipeline
-- Run these commands in Snowflake to set up the database structure

-- Create database if it doesn't exist
CREATE DATABASE IF NOT EXISTS FRAUD_DETECTION;

-- Create schema if it doesn't exist
CREATE SCHEMA IF NOT EXISTS FRAUD_DETECTION.PRODUCTION;

-- Create transactions_scored table
CREATE TABLE IF NOT EXISTS FRAUD_DETECTION.PRODUCTION.TRANSACTIONS_SCORED (
    TRANSACTION_ID VARCHAR(255),
    CUSTOMER_ID VARCHAR(255),
    AMOUNT FLOAT,
    FRAUD_PROBABILITY FLOAT,
    FRAUD_PREDICTION INTEGER,
    IS_FRAUD INTEGER,
    SCORE_TIME TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create metrics_daily table
CREATE TABLE IF NOT EXISTS FRAUD_DETECTION.PRODUCTION.METRICS_DAILY (
    DATE DATE,
    TRANSACTIONS INTEGER,
    FLAGGED INTEGER,
    AVG_RISK FLOAT,
    TOTAL_AMOUNT FLOAT,
    ACTUAL_FRAUD INTEGER,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS IDX_TRANSACTIONS_CUSTOMER_ID 
ON FRAUD_DETECTION.PRODUCTION.TRANSACTIONS_SCORED (CUSTOMER_ID);

CREATE INDEX IF NOT EXISTS IDX_TRANSACTIONS_SCORE_TIME 
ON FRAUD_DETECTION.PRODUCTION.TRANSACTIONS_SCORED (SCORE_TIME);

CREATE INDEX IF NOT EXISTS IDX_TRANSACTIONS_FRAUD_PREDICTION 
ON FRAUD_DETECTION.PRODUCTION.TRANSACTIONS_SCORED (FRAUD_PREDICTION);

CREATE INDEX IF NOT EXISTS IDX_METRICS_DATE 
ON FRAUD_DETECTION.PRODUCTION.METRICS_DAILY (DATE);

-- Grant permissions (adjust as needed for your environment)
-- GRANT USAGE ON DATABASE FRAUD_DETECTION TO ROLE YOUR_ROLE;
-- GRANT USAGE ON SCHEMA FRAUD_DETECTION.PRODUCTION TO ROLE YOUR_ROLE;
-- GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA FRAUD_DETECTION.PRODUCTION TO ROLE YOUR_ROLE;

-- Create a view for high-risk transactions
CREATE OR REPLACE VIEW FRAUD_DETECTION.PRODUCTION.HIGH_RISK_TRANSACTIONS AS
SELECT 
    TRANSACTION_ID,
    CUSTOMER_ID,
    AMOUNT,
    FRAUD_PROBABILITY,
    FRAUD_PREDICTION,
    IS_FRAUD,
    SCORE_TIME,
    CASE 
        WHEN FRAUD_PROBABILITY >= 0.8 THEN 'CRITICAL'
        WHEN FRAUD_PROBABILITY >= 0.6 THEN 'HIGH'
        WHEN FRAUD_PROBABILITY >= 0.4 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS RISK_LEVEL
FROM FRAUD_DETECTION.PRODUCTION.TRANSACTIONS_SCORED
WHERE FRAUD_PROBABILITY >= 0.4
ORDER BY FRAUD_PROBABILITY DESC;

-- Create a view for daily fraud summary
CREATE OR REPLACE VIEW FRAUD_DETECTION.PRODUCTION.DAILY_FRAUD_SUMMARY AS
SELECT 
    DATE,
    TRANSACTIONS,
    FLAGGED,
    ACTUAL_FRAUD,
    ROUND(AVG_RISK, 4) AS AVG_RISK,
    TOTAL_AMOUNT,
    ROUND((FLAGGED::FLOAT / TRANSACTIONS::FLOAT) * 100, 2) AS FLAG_RATE_PCT,
    ROUND((ACTUAL_FRAUD::FLOAT / TRANSACTIONS::FLOAT) * 100, 4) AS ACTUAL_FRAUD_RATE_PCT,
    CASE 
        WHEN ACTUAL_FRAUD > 0 THEN ROUND((FLAGGED::FLOAT / ACTUAL_FRAUD::FLOAT) * 100, 2)
        ELSE 0
    END AS RECALL_PCT
FROM FRAUD_DETECTION.PRODUCTION.METRICS_DAILY
ORDER BY DATE DESC;
